import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/component/nav'

import { config } from '@fortawesome/fontawesome-svg-core'



// 전역으로 쓸수 있게 세팅

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create aaaaaaaaaaa Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav/>
      {/* <p>글로벌 레이아웃1</p> */}
        {children}</body>
    </html>
  )
}
